### PR TITLE
Spark Stage Retry Handling

### PR DESCRIPTION
**Pull request by bvaradar**

### CODE REVIEW

**Comment by bvaradar** [comment]
@vinothchandar @n3nash : Unit tests passes now. Ready for review

**Comment by vinothchandar** [comment]
this PR is here, coz github does not support stacked diffs?

**Comment by bvaradar** [comment]
@vinothchandar : Yes, I created this PR against timeline_server branch

**Comment by bvaradar** [comment]
Closing this as dup of https://github.com/apache/incubator-hudi/pull/651

**Pull request closed without merging**
